agent: ppo
d_actor: 512
d_critic: 512
num_envs: 8
rollout_len: 32
sequence_length: 8
gamma: 0.99
gae_lambda: 0.97
num_minibatches: 8
update_epochs: 4
norm_adv: true

clip_coef: 0.2

history_len: 3

ent_coef:
  initial: 0.005
  final: 0.0001
  max_decay_steps: 80000000
  power: 1

vf_coef: 1.0
max_grad_norm: 0.2

adaptive_lr:
  enabled: true
  kl_threshold: 0.02
  lr_min: 1e-6
  lr_max: 1e-2

defaults:
  - _self_
  - seq_model: gru
